// The reviewed target19 schema + table list. DATA ONLY, no functions.
// See storage.ts's barrel header for why this lives outside the functions
// that consume it (assertTargetDataset, decodeArrowRows via describeField).
/**
 * `mcp_calls` and `connections` below are declared here, part of the
 * reviewed 19, but are NOT reachable through this dataset today.
 *
 * DECISIONS.md R5 (#103, #102): both are operations tables, written on every
 * admitted request straight to `ARRA_DATA_DIR` (`mcp/calls.ts`,
 * `mcp/connections.ts`) -- never through this gated knowledge dataset, and
 * never behind the exclusive writer gate this module enforces. The
 * `listMcpCalls`/`listConnections` readers (`knowledge/registry.ts`'s
 * `operations` entries, `mcp/calls.listMcpCalls.ts`,
 * `mcp/connections.listConnections.ts`) read `ARRA_DATA_DIR` for the same
 * reason. The copies of these two tables IN THIS dataset stay declared, so
 * `assertTargetDataset` keeps verifying their shape, but they stay EMPTY
 * until #34 migrates the operations tables over -- do not read them from
 * here as evidence that nothing was ever recorded.
 */
export const TARGET_SCHEMA: Readonly<Record<string, ReadonlyArray<readonly [string, string, boolean]>>> =
  Object.freeze({
  workspaces: [["id", "utf8", false], ["name", "utf8", false], ["created_at", "timestamp[us]", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true], ["configuration", "utf8", true], ["mission", "utf8", true]],
  peers: [["id", "utf8", false], ["name", "utf8", false], ["workspace_name", "utf8", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true], ["configuration", "utf8", true], ["created_at", "timestamp[us]", false]],
  sessions: [["id", "utf8", false], ["name", "utf8", false], ["workspace_name", "utf8", false], ["is_active", "bool", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true], ["configuration", "utf8", true], ["created_at", "timestamp[us]", false]],
  session_peers: [["workspace_name", "utf8", false], ["session_name", "utf8", false], ["peer_name", "utf8", false], ["configuration", "utf8", true], ["internal_metadata", "utf8", true], ["joined_at", "timestamp[us]", false], ["left_at", "timestamp[us]", true]],
  messages: [["id", "int64", false], ["public_id", "utf8", false], ["workspace_name", "utf8", false], ["session_name", "utf8", false], ["peer_name", "utf8", false], ["content", "utf8", false], ["token_count", "int64", false], ["seq_in_session", "int64", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true], ["created_at", "timestamp[us]", false], ["role", "utf8", true], ["in_reply_to", "utf8", true], ["read", "bool", true], ["read_at", "timestamp[us]", true], ["source_namespace", "utf8", true], ["source_message_id", "utf8", true], ["source_payload_digest", "utf8", true], ["source_created_at", "timestamp[us]", true], ["ingested_at", "timestamp[us]", false]],
  session_links: [["id", "utf8", false], ["workspace_name", "utf8", false], ["from_session_name", "utf8", false], ["to_session_name", "utf8", false], ["relation", "utf8", false], ["evidence_ref", "utf8", true], ["created_by_peer_name", "utf8", true], ["created_at", "timestamp[us]", false]],
  nodes: [["id", "utf8", false], ["workspace_name", "utf8", false], ["current_revision_id", "utf8", true], ["created_at", "timestamp[us]", false], ["updated_at", "timestamp[us]", false]],
  node_revisions: [["id", "utf8", false], ["workspace_name", "utf8", false], ["node_id", "utf8", false], ["revision_no", "int64", false], ["base_revision_id", "utf8", true], ["operation_id", "utf8", false], ["title", "utf8", false], ["body", "utf8", false], ["body_format", "utf8", false], ["fields", "utf8", false], ["author_peer_name", "utf8", true], ["observer_peer_name", "utf8", true], ["subject_peer_name", "utf8", true], ["session_name", "utf8", true], ["is_active", "bool", false], ["valid_from", "timestamp[us]", true], ["valid_to", "timestamp[us]", true], ["change_reason", "utf8", true], ["created_at", "timestamp[us]", false], ["schema_version", "int64", false], ["canonical_version", "utf8", false], ["content_digest", "utf8", false], ["term_snapshot_json", "utf8", false], ["link_snapshot_json", "utf8", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true]],
  node_revision_terms: [["workspace_name", "utf8", false], ["revision_id", "utf8", false], ["term_id", "utf8", false], ["vocabulary_id", "utf8", false], ["vocabulary_name_snapshot", "utf8", false], ["term_name_snapshot", "utf8", false], ["label_snapshot", "utf8", true], ["position", "int64", false]],
  revision_links: [["workspace_name", "utf8", false], ["revision_id", "utf8", false], ["position", "int64", false], ["relation", "utf8", false], ["target_kind", "utf8", false], ["target", "utf8", false], ["target_key", "utf8", false], ["excerpt", "utf8", true], ["content_hash", "utf8", true], ["captured_at", "timestamp[us]", true], ["capture_status", "utf8", false], ["note", "utf8", true]],
  supersede_log: [["id", "int64", false], ["workspace_name", "utf8", false], ["old_id", "utf8", false], ["old_revision_id", "utf8", false], ["old_title", "utf8", true], ["old_type", "utf8", true], ["old_source", "utf8", true], ["new_id", "utf8", true], ["new_revision_id", "utf8", true], ["new_title", "utf8", true], ["new_source", "utf8", true], ["reason", "utf8", false], ["peer_name", "utf8", true], ["superseded_at", "timestamp[us]", false], ["operation_id", "utf8", false], ["h_metadata", "utf8", true]],
  vocabularies: [["id", "utf8", false], ["name", "utf8", false], ["workspace_name", "utf8", false], ["label", "utf8", false], ["description", "utf8", true], ["kind", "utf8", false], ["term_policy", "utf8", false], ["cardinality", "utf8", false], ["required", "bool", false], ["hierarchy", "utf8", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true], ["created_at", "timestamp[us]", false]],
  terms: [["id", "utf8", false], ["workspace_name", "utf8", false], ["vocabulary_id", "utf8", false], ["name", "utf8", false], ["description", "utf8", true], ["parent_id", "utf8", true], ["weight", "float64", false], ["is_active", "bool", false], ["h_metadata", "utf8", true], ["created_at", "timestamp[us]", false]],
  traces: [["id", "utf8", false], ["name", "utf8", false], ["workspace_name", "utf8", false], ["session_name", "utf8", true], ["peer_name", "utf8", true], ["query", "utf8", false], ["mode", "utf8", true], ["session_id", "utf8", true], ["session_from_ts", "int64", true], ["session_to_ts", "int64", true], ["friction_score", "float64", true], ["confidence", "utf8", true], ["parent_id", "utf8", true], ["prev_id", "utf8", true], ["depth", "int64", false], ["status", "utf8", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true], ["created_at", "int64", false], ["updated_at", "int64", false]],
  trace_hits: [["workspace_name", "utf8", false], ["trace_id", "utf8", false], ["kind", "utf8", false], ["ref", "utf8", false], ["target", "utf8", false], ["line_start", "int64", true], ["line_end", "int64", true], ["excerpt", "utf8", true], ["content_hash", "utf8", true], ["captured_at", "timestamp[us]", true], ["note", "utf8", true], ["position", "int64", false]],
  search_chunks_v1: [["id", "utf8", false], ["workspace_name", "utf8", false], ["node_id", "utf8", false], ["revision_id", "utf8", false], ["chunk_index", "int64", false], ["text", "utf8", false], ["content_hash", "utf8", false], ["chunker_version", "utf8", false], ["embedding_profile", "utf8", false], ["embedding", "fixed_size_list<float32?>[384]", true], ["type_term_id", "utf8", false], ["term_ids", "list<utf8?>", false], ["observer_peer_name", "utf8", true], ["subject_peer_name", "utf8", true], ["session_name", "utf8", true], ["status", "utf8", false], ["attempts", "int64", false], ["last_attempt_at", "timestamp[us]", true], ["embedded_at", "timestamp[us]", true], ["error_code", "utf8", true]],
  mcp_calls: [["id", "utf8", false], ["workspace_name", "utf8", false], ["session_name", "utf8", true], ["peer_name", "utf8", true], ["tool", "utf8", false], ["status", "utf8", false], ["duration_ms", "int64", false], ["h_metadata", "utf8", true], ["internal_metadata", "utf8", true], ["created_at", "int64", false], ["connection_id", "utf8", true], ["principal", "utf8", true]],
  connections: [["id", "utf8", false], ["workspace_name", "utf8", false], ["method", "utf8", false], ["principal", "utf8", false], ["label", "utf8", false], ["user_agent", "utf8", true], ["remote_ip", "utf8", true], ["first_seen", "timestamp[us]", false], ["last_seen", "timestamp[us]", false], ["requests", "int64", false], ["tool_calls", "int64", false], ["last_tool", "utf8", true]],
  read_cursors: [["workspace_name", "utf8", false], ["peer_name", "utf8", false], ["session_name", "utf8", false], ["last_read_message_id", "utf8", true], ["last_read_at", "timestamp[us]", false]],
  }) as never;

/** The 19 reviewed target tables, in golden order. */
export const TARGET_TABLES = Object.freeze(Object.keys(TARGET_SCHEMA)) as readonly string[];
